<a href="https://colab.research.google.com/github/sivaa2308/ML-Projects/blob/main/Notebooks/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
import sys

In [ ]:
t1=time.time()
t2=time.time()
print(t2-t1)

6.437301635742188e-05


In [ ]:
x=[1,2,3,4,5,6,8]
start=time.time()
new=x*10000
print(new)
l=len(new)
print(time.time()-start)
print(l)

[1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 

In [ ]:
import sys
print(sys.version)

3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]



**sys.stdin**

In [ ]:
import sys

for line in sys.stdin:
    if 'q' == line.rstrip():
        break
    print(f'Input : {line}')
print("Exit")

Exit


**arr.nbytes**

In [ ]:
import numpy as np
import sys
list1=[1,2,3,4,5,6,7,8]
arr=np.array(list1)
print(sys.getsizeof(list1))
print(arr.nbytes)

120
64


In [ ]:
import sys
list1=[int(x) for x in range(10)]
print(sys.getsizeof(list1))
list1

184


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import numpy as np
import sys
a=np.arange(0,10 ,2)
print(a)
print(sys.getsizeof(a)) # this is the whole space occupied in the memory incluiding meta data
print(a.nbytes) #this is the space occupied by the array only
a

[0 2 4 6 8]
152
40


array([0, 2, 4, 6, 8])

In [ ]:
import numpy as np
arr=np.linspace(0,20,100)  #this function is used for making values between 2 - 20 with 10 values
arr

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [ ]:
arr=np.logspace(1,3,6)#logarithamiic values from 10^1 - 10^3....3
arr

array([  10.        ,   25.11886432,   63.09573445,  158.48931925,
        398.10717055, 1000.        ])

In [ ]:
arr=np.zeros(5) #this is used to create an array of zeroes of size which is given as parameter
brr=np.zeros([3,3])
print(arr)
print(brr)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones(6)
print(arr)
arr=np.ones([3,3])
print(arr)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.empty([2,3]) #used to create an uninitialized array
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
for i in range(10,0,-1):
    print(i*"*")

**********
*********
********
*******
******
*****
****
***
**
*


In [ ]:
for i in range(10):
    print(i*"*")


*
**
***
****
*****
******
*******
********
*********


In [ ]:
x=10
for i in range(x):
  print(i*"*")
for i in range(x,0,-1):
  print(i*"*")


*
**
***
****
*****
******
*******
********
*********
**********
*********
********
*******
******
*****
****
***
**
*


In [ ]:
x=10
for i in range(x,0,-1):
  print(i*"*")
for i in range(2,x+1):
  print(i*"*")

**********
*********
********
*******
******
*****
****
***
**
*
**
***
****
*****
******
*******
********
*********
**********


In [ ]:
x=10
for i in range(x+1):
  print(i*"*"+" "*(x*2)+i*"*")
  x-=1

                    
*                  *
**                **
***              ***
****            ****
*****          *****
******        ******
*******      *******
********    ********
*********  *********
********************


In [ ]:
x=10
n=0
for i in range(x+1,0,-1):
  print(i*"*"+" "*(n*2)+i*"*")
  n+=1
x=11
for i in range(x+1):
  print(i*"*"+" "*(x*2)+i*"*")
  x-=1

**********************
**********  **********
*********    *********
********      ********
*******        *******
******          ******
*****            *****
****              ****
***                ***
**                  **
*                    *
                      
*                    *
**                  **
***                ***
****              ****
*****            *****
******          ******
*******        *******
********      ********
*********    *********
**********  **********
**********************


In [ ]:
x=10
for i in range(x+1):
  print(" "*x+"*"*i+"*"*i)
  x-=1

          
         **
        ****
       ******
      ********
     **********
    ************
   **************
  ****************
 ******************
********************


In [ ]:
import numpy as np
arr=np.random.rand() #This is used to create random floats
brr=np.random.rand(10) #THis is used to create random values array
print(brr)
print(arr)
print(round(arr,3))

[0.62371941 0.59104754 0.3648931  0.44580133 0.31146366 0.68906198
 0.00454072 0.67187834 0.54917654 0.2243429 ]
0.21902998706566545
0.219


In [ ]:
import random

arr = random.random()
print(round(arr,2))


0.65


In [ ]:
arr=np.random.randint(10,100,size=(2,3))
arr

array([[26, 78, 72],
       [62, 26, 32]])

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

new=arr.astype(np.float64)
print(new)
print(new.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


**Array reshape**

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape)
reshaped=arr.reshape(2,3)
print(reshaped)
print(reshaped.shape)
reshaped1=reshaped.reshape(3,2)
print(reshaped1)
print(reshaped1.shape)



[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


**flaten**

In [ ]:
flat=arr.flatten() #The flatten and the ravel are functionaly same , but flatten only change the value of the copy , while ravel change entire related arrays vaue
print(flat)
print(flat.shape)
flat[0]=101
print(flat)
print(arr)

[102   2   3   4   5   6]
(6,)
[101   2   3   4   5   6]
[102   2   3   4   5   6]


**Ravel**

In [ ]:
ravel=reshaped1.ravel() #The flatten and the ravel are functionaly same , but flatten only change the value of the copy , while ravel change entire related arrays vaue
print(ravel)
print(ravel.shape)
ravel[0]=102
print(ravel)
print(reshaped1)

[100   2   3   4   5   6]
(6,)
[102   2   3   4   5   6]
[[102   2]
 [  3   4]
 [  5   6]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a*b)


[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 2 3]
[ 4 10 18]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1:,2:])
print(a[1,2:])
print(a[1:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[7 8]
[ 7 11]


**np.take**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])  #this np.take selects the values from the list from the index defined on another list
index=[0,3]
print(np.take(arr,index))

[1 4]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  #the nd.iter is the methode to loop through the array in the numpy , normal for loop will not work in this

for i in np.nditer(a):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

for ind , x in np.ndenumerate(a):
  print(ind,x)

print(a)
print(a.transpose())

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=np.array([[13,14,15,16],[17,18,19,20],[21,22,23,24]])
print("Vstack")
print(np.vstack((a,b)))
print("Hstack")
print(np.hstack((a,b)))

Vstack
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Hstack
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.split(a,3))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.repeat(a,4))
print(np.tile(a,4))

[ 1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5  6  6  6  6
  7  7  7  7  8  8  8  8  9  9  9  9 10 10 10 10 11 11 11 11 12 12 12 12]
[[ 1  2  3  4  1  2  3  4  1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8  5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12  9 10 11 12  9 10 11 12]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))

78
6.5
6.5
11.916666666666666
1
12


In [ ]:
print(np.sum(a, axis=0))

[15 18 21 24]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.cumsum(a))
print(np.cumprod(a))
print(np.argwhere(a>3))  #The line in Python using NumPy is used to find the indices of elements in the array a that satisfy the condition a > 3


[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
mask=np.logical_and(a>2 , a<7)
print(mask)
print(a[mask])
mask1=np.logical_or(a>2 , a<7)
print(mask1)
print(a[mask1])

[False False  True  True  True  True False False False False]
[3 4 5 6]
[ True  True  True  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.where((a > 4) & (a > 6)) )
print(np.take(a, 3, axis=None))


(array([6, 7, 8, 9]),)
4


In [ ]:
l1 = [1, 3, 5, 7, 9]
l2 = [2, 4, 6, 8, 10]
i, j = 0, 0

while i < len(l1) and j < len(l2):
    if l1[i] < l2[j]:
        print(l1[i])
        i += 1
    else:
        print(l2[j])
        j += 1

while i < len(l1):
    print(l1[i])
    i += 1

while j < len(l2):
    print(l2[j])
    j += 1


1
2
3
4
5
6
7
8
9
10


**Broadcasting**

Broadcasting is a NumPy feature that allows operations between arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one — without copying data unnecessarily.

In [ ]:
image=np.array([[200,250],[300,350]])
print(image.shape)
image+=50
print(image)

(2, 2)
[[250 300]
 [350 400]]


In [ ]:
l1=[[[1,2],[3,4]],[[5,6],[7,8]]]
a=np.array(l1)
print(a.shape)

(2, 2, 2)


**np.vectorize**

np.vectorize is a convenience wrapper to apply a function element-wise over NumPy arrays (like Python's map() but NumPy-aware).

In [ ]:
def square(x):
  return x*x
square(9)

vfactor=np.vectorize(square)
print(vfactor(a))

[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


**np.nan**

np.nan stands for "Not a Number", and it is used to represent missing or undefined numeric values — like a placeholder for invalid or empty data in floating-point arrays.

In [ ]:
arr = np.array([1, 2, np.nan, 4])
b=[1,2,3,4,np.inf,5]
print(arr)
print(np.isnan(arr))
print(np.isinf(b))
arr=np.nan_to_num(arr,nan=0)
b=np.nan_to_num(b,posinf=10000,neginf=-100000)  # remove not a number or infinet values
print(arr)
print(b)

[ 1.  2. nan  4.]
[False False  True False]
[False False False False  True False]
[1. 2. 0. 4.]
[1.e+00 2.e+00 3.e+00 4.e+00 1.e+04 5.e+00]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.where(a>6))
print((a>5)&(a>8))
print(np.logical_and(a>5 , a>8))

(array([6, 7, 8]),)
[False False False False False False False False  True]
[False False False False False False False False  True]


**np.power**

np.power(arr1, arr2) raises each element of arr1 to the power of the corresponding element in arr2, element-wise.

In [ ]:
import numpy as np

arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 2, 1])

result = np.power(arr1, arr2)
print(result)


[8 9 4]


In [ ]:
num=[]
num1=[]
pow=-1
ans=1
while(ans<=10**9):
  pow+=1
  ans=2**pow
  num.append(ans)
num1=num[8].split()
print(len(num))
print(num1)

AttributeError: 'int' object has no attribute 'split'

In [ ]:
n=int(input())
stat=False
n_sorted = ''.join(sorted(str(n)))
for i in range(31):
  pow=2**i
  pow_sort=''.join(sorted(str(pow)))
  if pow_sort==n_sorted:
    print(True)
    stat=True
    break
if stat==False:
  print(False)

658578
False
